config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  resources :books
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController


  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = "Book was successfully created."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      render :index
    end
  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "Book was successfully updated."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    flash[:notice] = "Book was successfully destroyed."
    redirect_to '/books'
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h2>Editing Book</h2>
<% if @book.errors.any? %>
  <%= @book.errors.count %> errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @book do |f| %>

  <p>Title</p>
  <%= f.text_field :title, class: "follow_title" %>

  <p>Body</p>
  <%= f.text_area :body, class: "follow_body" %>

  <%= f.submit 'Update Book', class: "follow_submit" %>

  <%= link_to "show", book_path(@book.id), class: "follow_show_edit" %>
  <%= link_to "Back", books_path(@books), class: "follow_Back" %>

<% end %>

app/views/books/index.html.erb
<div class="flash_color">
  <%= flash[:notice] %>
</div>

<h1>Books</h1>
　<table>
　  <thead>
　  <tr>
      <th>Title</th>
      <th>Body</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
    </thead>
    <% @books.each do |book| %>
    <tbody class="bookList">
      <tr>
      <td class="bookListTitle"><%= book.title %></td>
      <td class="bookListBody"><%= book.body %></td>
      <td class="bookListShow"><%= link_to "show", book_path(book.id) %></td>
      <td class="bookListEdit"><%= link_to "Edit", edit_book_path(book.id) %></td>
      <td class="bookListDestroy"><%= link_to "Destroy", book_path(book.id), method: :delete, "data-confirm" => "Are you sure?" %></td>
    </tr>
    </tbody>
    <% end %>
  </table>


<h2>New book</h2>
<% if @book.errors.any? %>
  <%= @book.errors.count %> errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @book, url: '/books', method: :post do |f| %>

  <h6>Title</h6>
  <%= f.text_field :title, class: "follow_title" %>

  <h6>Body</h6>
  <%= f.text_area :body, class: "follow_body" %>

  <%= f.submit 'Create Book', class: "follow_submit" %>

<% end %>

app/views/books/show.html.erb
<div class="flash_color">
  <%= flash[:notice] %>
</div>

<div class="showViews">
  <div class="showViewsTitle">
    <b class="showTitleBodyLeft">Title:</b>
    <p class="showTitleBodyRight"><%= @book.title %></p>
  </div>

  <div class="showViewsBody">
    <b class="showTitleBodyLeft">Body:</b>
    <p class="showTitleBodyRight"><%= @book.body %></p>
  </div>
</div>

<%= link_to "Edit", edit_book_path(@book.id), class: "follow_show_edit" %>
<%= link_to "Back", books_path(@books), class: "follow_Back" %>

app/views/homes/top.html.erb
<h1>ようこそ Bookers へ！</h1>
<!--<p>Find me in app/views/homes/top.html.erb</p>-->
<p class="top-title">
  Bookersでは、さまざまな書籍に関するあなたの意見や<br>
  <br>

  印象を共有し交換することができます<br>
  <br>


<%= link_to "start", books_path(@books) %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>